apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: baktha/myapi:0.0.1
        imagePullPolicy: IfNotPresent
        command: ["gunicorn"  , "-b", "0.0.0.0:9000", "electricity_api.wsgi"]
        env:
        ports:
        - name: http
          containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000